{% set name = "thriftpy2" %}
{% set version = "0.4.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a6326d82dc2b7edb364607041715645e64256949680c9a549a1258d74ef625d

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - ply >=3.4,<4.0
    - python

test:
  imports:
    - thriftpy2
    - thriftpy2.parser
    - thriftpy2.protocol
    - thriftpy2.transport

about:
  home: https://thriftpy2.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python implementation of Apache Thrift.
  doc_url: https://thriftpy2.readthedocs.io/
  dev_url: https://github.com/Thriftpy/thriftpy2/

extra:
  recipe-maintainers:
    - xhochy
