{% set name = "thriftpy2" %}
{% set version = "0.4.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2aa67ecda99a948e4146341d388260b48ee7da5dfb9a951c4151988e2ed2fb4c

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - cython <3
    - python
  run:
    - six >=1.15,<2.dev0
    - ply >=3.4,<4.0
    - python

test:
  imports:
    - thriftpy2
    - thriftpy2.parser
    - thriftpy2.protocol
    - thriftpy2.transport

about:
  home: https://thriftpy2.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python implementation of Apache Thrift.
  doc_url: https://thriftpy2.readthedocs.io/
  dev_url: https://github.com/Thriftpy/thriftpy2/

extra:
  recipe-maintainers:
    - xhochy
