{% set name = "thriftpy2" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ade0165ba060b97333bc7a927229e992441bfa17bb8e13ea05590c2ec3551b17

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.28.4,<4                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - cython >=3,<4
    - toml
    - setuptools >=68
  run:
    - six >=1.15,<2.dev0
    - ply >=3.4,<4.0
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - thriftpy2
    - thriftpy2.parser
    - thriftpy2.protocol
    - thriftpy2.transport

about:
  home: https://thriftpy2.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python implementation of Apache Thrift.
  doc_url: https://thriftpy2.readthedocs.io/
  dev_url: https://github.com/Thriftpy/thriftpy2/

extra:
  recipe-maintainers:
    - xhochy
